development:
  sessions:
    default:
      database: touch_type_in_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: touch_type_in_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: touch_type_in_production
      hosts:
        - localhost:27017